### PR TITLE
Fixes issue Maarten

### PR DESCRIPTION
**Pull request by siebrenf**
sorry, my bad. Seems I'm getting used to Python doing some steps for me :)

**What problem is the PR solving / What's new?**
A description of the problem that is being solved, or which new feature is implemented. Please link to other relevant issues/pr if relevant

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions? What did you try? What didn't work?

**Does this need additional test(s)?**
If implementing new features let us know, so we can generate appropriate tests.

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Is this what I need for RNA-seq? :)

**Comment by siebrenf** [comment]
yes, the thing you send in the slack

**Comment by Maarten-vd-Sande** [comment]
blind clustering passed

**Comment by Maarten-vd-Sande** [comment]
deseq2 as well :tada:

**Pull request merged**
