### PR TITLE
Update configuration.smk

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
This should at least catch some of in #253

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
This gives an error btw xD

**Comment by siebrenf** [comment]
no error, but Test DAG and Test Downloading keep returning
`Possible unintended interpolation of @2 in string at /var/lib/jenkins/workspace/snakemake-workflows_PR-255@2/miniconda/envs/snakemake-workflows/lib/5.26.2/x86_64-linux-thread-multi/Config_heavy.pl line 260.
`

**Comment by Maarten-vd-Sande** [comment]
How does this work when people just downloaded it (not through git)?

**Comment by Maarten-vd-Sande** [comment]
And not sure what causes the warming. Did you check which of the two commands causes it?

**Comment by siebrenf** [comment]
It's working!

**Comment by Maarten-vd-Sande** [comment]
Hooray :tada:

**Pull request merged**
