### PR TITLE
Prettier badge

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
Now that our testing results are so pretty, we should show them off to the world :wink: !

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Yikes, I branched from master, and did not expect all this mess to come along. Why/what is the difference between master and develop? Not sure which one is correct..

**Comment by Maarten-vd-Sande** [comment]
I'll restart from develop, but keeping this open for now for the answer

**Comment by siebrenf** [comment]
Master and develop should be identical. any changes (other than yours) are likely due to the... Uhm.. experiments with the revert feature.

**Comment by Maarten-vd-Sande** [comment]
The differences are quite large

**Comment by siebrenf** [comment]
All changes from #250 are already present, so it must be issues with Revert. Lets hope this will fix it!

**Pull request merged**
