### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by siebrenf**
bugfixes & optimizations galore!

### CODE REVIEW

**Comment by siebrenf** [comment]
Jenkins now uses a unique NCBI key to prevent clashes

**Comment by Maarten-vd-Sande** [comment]
Adding a mutex lock around layouts.p is I think a slightly better solution, but both work :).

**Comment by siebrenf** [comment]
Yes, that would a future proof solution! I'll add it to the issues for later integration.

**Comment by Maarten-vd-Sande** [comment]
Would be nice if there is some mutex lock that both bash and python understand. That way we could actually have multiple downloads at the same time (id2sra).

**Pull request merged**
