### PR TITLE
Update trackhub.smk

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
@JGASmits can you try this one?

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
@JGASmits if it works you can accept the changes, the big red button should turn green and you can click squash and merge :)

**Comment by Maarten-vd-Sande** [comment]
@siebrenf I am afraid we will have to make a little dictionary/schema/sth that tells us the conversion

**Comment by Maarten-vd-Sande** [comment]
`curl -L 'https://api.genome.ucsc.edu/list/ucscGenomes'`

Gives a json that looks like this:
```
    "hg19": {
      "description": "Feb. 2009 (GRCh37\/hg19)",
      "nibPath": "\/gbdb\/hg19",
      "organism": "Human",
      "defaultPos": "chr21:33,031,597-33,041,570",
      "active": 1,
      "orderKey": 60,
      "genome": "Human",
      "scientificName": "Homo sapiens",
      "htmlPath": "\/gbdb\/hg19\/html\/description.html",
      "hgNearOk": 1,
      "hgPbOk": 0,
      "sourceName": "GRCh37 Genome Reference Consortium Human Reference 37 (GCA_000001405.1)",
      "taxId": 9606
    },
    "hg38": {
      "description": "Dec. 2013 (GRCh38\/hg38)",
      "nibPath": "\/gbdb\/hg38",
      "organism": "Human",
      "defaultPos": "chr1:11102837-11267747",
      "active": 1,
      "orderKey": 50,
      "genome": "Human",
      "scientificName": "Homo sapiens",
      "htmlPath": "\/gbdb\/hg38\/html\/description.html",
      "hgNearOk": 1,
      "hgPbOk": 0,
      "sourceName": "GRCh38 Genome Reference Consortium Human Reference 38 (GCA_000001405.15)",
      "taxId": 9606
    },
```

We should be able to parse this relatively easy :)

**Comment by JGASmits** [comment]
Ill try the Maarten-vd-Sande-patch-1 with the trackhub! :)

**Pull request merged**
