### PR TITLE
fixes #108

### LINKED ISSUE #108: Trim galore! causes rule ambiguity
Seems like a bug in snakemake as a rule order is given. However, this issue may be fixable as the error message reveals `rule trim_galore_SE` is adding _pass_1 to the wildcard:
```
AmbiguousRuleException:
Rules trim_galore_PE and trim_galore_SE are ambiguous for the file /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1_trimmed.fastq.gz.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        trim_galore_PE: sample=GSM2837484
        trim_galore_SE: sample=GSM2837484_pass_1
Expected input files:
        trim_galore_PE: /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1.fastq.gz /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_2.fastq.gz
        trim_galore_SE: /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1.fastq.gz
Expected output files:
        trim_galore_PE: /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1_trimmed.fastq.gz /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_2_trimmed.fastq.gz /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1.fastq.gz_trimming_report.txt /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_2.fastq.gz_trimming_report.txt
        trim_galore_SE: /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1_trimmed.fastq.gz /home/siebrenf/git/snakemake-workflows/workflows/alignment/FASTQ/GSM2837484_pass_1.fastq.gz_trimming_report.txt
```
this may be resolved by using a wildcard constraint

### PR DESCRIPTION
**Pull request by siebrenf**

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Sorry, I destroyed the automated tests by trying to implement cache for faster testing. However when I run
`snakemake -s workflows/atac_seq/Snakefile       --directory workflows/atac_seq       -n -j 48`
in this branch I get:
MissingInputException in line 64 of /home/sande/Dropbox/Studie/PhD/snakemake-workflows/rules/get_fastq.smk:
```
Missing input files for rule sra2fastq_SE:
/home/sande/Dropbox/Studie/PhD/snakemake-workflows/workflows/atac_seq/sra/GSM2520641_trimmed
```

**Comment by siebrenf** [comment]
That error is unrelated to the changes(?)

**Comment by Maarten-vd-Sande** [comment]
My guess is not, since the master branch does not have the same problem.

**Comment by Maarten-vd-Sande** [comment]
@siebrenf I fixed the tests and pulled them. The wildcard constraints cause the error

**Comment by Maarten-vd-Sande** [comment]
@siebrenf I changed the tests to reflect these changes (only performed once)

**Comment by Maarten-vd-Sande** [comment]
Out of the 16 tests no ambiguity was found, so I'm assuming it works :tada: !!

**Pull request merged**
