### PR TITLE
Global mutex lock

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
layouts.p is now stored in .config/snakemake.layouts.p. The filelock is now "global", in the sense that each user has a layouts and a lock around it. If people were to use ncbi keys on e.g. mb07, they should (?) never interfere with each other.

Since we have a global filelock we can re-use this for our id2sra rule, which means that the downloading can now we done in parallel!! (I set the default to 3)

Note that in the tests the downloading also happens in parallel :)

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
p.s. I have no clue why the commits from the previous PR came along. I tried switching branch but it didnt work. It doesn't matter since they are identical to develop anyways.

**Comment by siebrenf** [comment]
Ok, so for my understanding:
- why don't we need the NCBI key anymore?
- the file lock prevents multiple layout searches, but what prevents multiple tests from downloading the same sample simultaneously?

**Comment by Maarten-vd-Sande** [comment]
Nothing prevents downloading the same stuff at the same time except snakemake locking folders, but our previous solution didn't do anything about that either right?

Every time you do something that uses the e-utils (checking layouts and downloading sra), we now put a "lock" around the layouts.p file. When this lock exists other rules that want to use the e-utils will wait untill the lock is released.  We dont need the NCBI key anymore to bypass the problem of multiple searches.

**Comment by Maarten-vd-Sande** [comment]
Wait, I just realized I am stupid. The downloads won't happen in parallel, they just block each other....

**Comment by siebrenf** [comment]
wont the NCBI key speed up the rule that is running either way?

**Comment by Maarten-vd-Sande** [comment]
It only speeds up the fetching of the layouts, which shouldn't take more than 10 seconds anyways.

**Comment by Maarten-vd-Sande** [comment]
Its not pretty, but now it should work! This is me downloading two files at the same time :)
ezgif com-video-to-gif(2)

**Pull request merged**
